[Metadata]
Name=战双帕弥什 · 21号
Version=0.9
Author=supergougou
Description=战双帕弥什·21号皮肤上线！
ScaleWithDPI=False

[InputPanel]
Font=Sans 15
NormalColor=#ffffff
HighlightCandidateColor=#400080
HighlightColor=#400080
HighlightBackgroundColor=#030202
Spacing=3

[InputPanel/TextMargin]
Left=5
Right=5
Top=10
Bottom=9

[InputPanel/ContentMargin]
Left=70
Right=175
Top=118
Bottom=31

[InputPanel/Background]
Image=skin1.png

[InputPanel/Background/Margin]
Left=147
Right=244
Top=3
Bottom=11

[InputPanel/Highlight]
Image=highlight.png

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/PrevPage]
Image=prev.png

[InputPanel/PrevPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[InputPanel/NextPage]
Image=next.png

[InputPanel/NextPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[Menu/Background]
Image=skin2.png

[Menu/Background/Margin]
Left=133
Right=180
Top=186
Bottom=67

[Menu/ContentMargin]
Left=64
Right=64
Top=128
Bottom=26

[Menu/Highlight]
Image=menu_highlight.png

[Menu/Highlight/Margin]
Left=10
Right=10
Top=5
Bottom=5

[Menu/Separator]
Color=#ffffff

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

