[Icon Theme]
Name=AnimeApps
Comment=An anime-based icon theme for Gnome and Plasma. It features some OS-Tans and famous anime characters.
FollowsColorScheme=true

DesktopDefault=48
DesktopSizes=16,22,32,48,64,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=48
PanelSizes=16,22,32,48,64,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256

KDE-Extensions=.png

Inherits=WhiteSur-dark,WhiteSur,hicolor

Directories=apps,places/scalable,

[apps]
Size=128
Context=Applications
Type=Scalable
MinSize=16
MaxSize=512

[places/scalable]
Size=128
Context=Places
Type=Scalable
MinSize=16
MaxSize=512
